package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.Recipe;
import com.hmaresc.TFG_Servidor.model.RecipeInstruction;
import com.hmaresc.TFG_Servidor.service.RecipeInstructionService;
import com.hmaresc.TFG_Servidor.service.RecipeService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/recipeinstruction")
public class RecipeInstructionController {

    @Autowired
    private RecipeInstructionService recipeInstructionService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /recipeinstruction/
    // .......................................................
    @GetMapping
    public List<RecipeInstruction> getAllRecipesInstruction() {
        return recipeInstructionService.getAllRecipesInstruction();
    }

    // .......................................................
    // GET /recipeinstruction/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<RecipeInstruction> getRecipeInstructionById(@PathVariable Long id) {
        Optional<RecipeInstruction> recipeInstruction = recipeInstructionService.getRecipeInstructionById(id);

        if (recipeInstruction.isPresent()) {
            return ResponseEntity.ok(recipeInstruction.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /recipeinstruction/
    // .......................................................
    @PostMapping
    public ResponseEntity<RecipeInstruction> createRecipeInstruction(@Valid @RequestBody RecipeInstruction recipeInstruction) {
        RecipeInstruction created = recipeInstructionService.createRecipeInstruction(recipeInstruction);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /recipeinstruction/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<RecipeInstruction> updateRecipeInstruction(@PathVariable Long id, @Valid @RequestBody RecipeInstruction recipeInstructionDetails) {
        Optional<RecipeInstruction> updatedRecipeInstruction = recipeInstructionService.updateRecipeInstruction(id, recipeInstructionDetails);
        return updatedRecipeInstruction.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /recipeinstruction/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRecipeInstruction(@PathVariable Long id) {
        boolean deleted = recipeInstructionService.deleteRecipeInstruction(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
