package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.Recipe;
import com.hmaresc.TFG_Servidor.model.RecipeFood;
import com.hmaresc.TFG_Servidor.service.RecipeFoodService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/recipefood")
public class RecipeFoodController {

    private RecipeFoodService recipeFoodService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /recipefood/
    // .......................................................
    @GetMapping
    public List<RecipeFood> getAllRecipesFoods() {
        return recipeFoodService.getAllRecipesFoods();
    }

    // .......................................................
    // GET /recipefood/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<RecipeFood> getRecipeFoodById(@PathVariable Long id) {
        Optional<RecipeFood> recipeFood = recipeFoodService.getRecipeFoodById(id);

        if (recipeFood.isPresent()) {
            return ResponseEntity.ok(recipeFood.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /recipefood/
    // .......................................................
    @PostMapping
    public ResponseEntity<RecipeFood> createRecipeFood(@Valid @RequestBody RecipeFood recipeFood) {
        RecipeFood created = recipeFoodService.createRecipeFood(recipeFood);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /recipefood/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<RecipeFood> updateRecipeFood(@PathVariable Long id, @Valid @RequestBody RecipeFood recipeFoodDetails) {
        Optional<RecipeFood> updatedRecipeFood = recipeFoodService.updateRecipeFood(id, recipeFoodDetails);
        return updatedRecipeFood.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /recipefood/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRecipeFood(@PathVariable Long id) {
        boolean deleted = recipeFoodService.deleteRecipeFood(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
