package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.RecipeIngredient;
import com.hmaresc.TFG_Servidor.service.RecipeIngredientService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/recipeingredient")
public class RecipeIngredientController {

    @Autowired
    private RecipeIngredientService recipeIngredientService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /recipeingredient/
    // .......................................................
    @GetMapping
    public List<RecipeIngredient> getAllRecipesIngredient() {
        return recipeIngredientService.getAllRecipesIngredient();
    }

    // .......................................................
    // GET /recipeingredient/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<RecipeIngredient> getRecipeIngredientById(@PathVariable Long id) {
        Optional<RecipeIngredient> recipeIngredient = recipeIngredientService.getRecipeIngredientById(id);

        if (recipeIngredient.isPresent()) {
            return ResponseEntity.ok(recipeIngredient.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /recipeingredient/
    // .......................................................
    @PostMapping
    public ResponseEntity<RecipeIngredient> createRecipeIngredient(@Valid @RequestBody RecipeIngredient recipeIngredient) {
        RecipeIngredient created = recipeIngredientService.createRecipeIngredient(recipeIngredient);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /recipeingredient/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<RecipeIngredient> updateRecipeIngredient(@PathVariable Long id, @Valid @RequestBody RecipeIngredient recipeIngredientDetails) {
        Optional<RecipeIngredient> updatedRecipeIngredient = recipeIngredientService.updateRecipeIngredient(id, recipeIngredientDetails);
        return updatedRecipeIngredient.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /recipeingredient/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRecipeIngredient(@PathVariable Long id) {
        boolean deleted = recipeIngredientService.deleteRecipeIngredient(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
