package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.Recipe;
import com.hmaresc.TFG_Servidor.model.TemperatureHumidity;
import com.hmaresc.TFG_Servidor.service.TemperatureHumidityService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/temhum")
public class TemperatureHumidityController {

    @Autowired
    private TemperatureHumidityService temperatureHumidityService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /temhum/
    // .......................................................
    @GetMapping
    public List<TemperatureHumidity> getAllTemperatureHumidity() {
        return temperatureHumidityService.getAllTemperatureHumidity();
    }

    // .......................................................
    // GET /temhum/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<TemperatureHumidity> getTemperatureHumidityById(@PathVariable Long id) {
        Optional<TemperatureHumidity> temperatureHumidity = temperatureHumidityService.getTemperatureHumidityById(id);

        if (temperatureHumidity.isPresent()) {
            return ResponseEntity.ok(temperatureHumidity.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /temhum/
    // .......................................................
    @PostMapping
    public ResponseEntity<TemperatureHumidity> createTemperatureHumidity(@Valid @RequestBody TemperatureHumidity temperatureHumidity) {
        TemperatureHumidity created = temperatureHumidityService.createTemperatureHumidity(temperatureHumidity);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /temhum/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<TemperatureHumidity> updateTemperatureHumidity(@PathVariable Long id, @Valid @RequestBody TemperatureHumidity temperatureHumidityDetails) {
        Optional<TemperatureHumidity> updatedTemperatureHumidity = temperatureHumidityService.updateTemperatureHumidity(id, temperatureHumidityDetails);
        return updatedTemperatureHumidity.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /temhum/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteTemperatureHumidity(@PathVariable Long id) {
        boolean deleted = temperatureHumidityService.deleteTemperatureHumidity(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
