package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.Recipe;
import com.hmaresc.TFG_Servidor.model.UsersRecipes;
import com.hmaresc.TFG_Servidor.service.UsersRecipesService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/usersrecipes")
public class UsersRecipesController {

    @Autowired
    private UsersRecipesService usersRecipesService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /usersrecipes/
    // .......................................................
    @GetMapping
    public List<UsersRecipes> getAllUsersRecipes() {
        return usersRecipesService.getAllUsersRecipes();
    }

    // .......................................................
    // GET /usersrecipes/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<UsersRecipes> getUsersRecipesById(@PathVariable Long id) {
        Optional<UsersRecipes> usersRecipes = usersRecipesService.getUsersRecipesById(id);

        if (usersRecipes.isPresent()) {
            return ResponseEntity.ok(usersRecipes.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /usersrecipes/
    // .......................................................
    @PostMapping
    public ResponseEntity<UsersRecipes> createUsersRecipes(@Valid @RequestBody UsersRecipes usersRecipes) {
        UsersRecipes created = usersRecipesService.createUsersRecipes(usersRecipes);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /usersrecipes/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<UsersRecipes> updateUsersRecipes(@PathVariable Long id, @Valid @RequestBody UsersRecipes usersRecipesDetails) {
        Optional<UsersRecipes> updatedUsersRecipes = usersRecipesService.updateUsersRecipes(id, usersRecipesDetails);
        return updatedUsersRecipes.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /usersrecipes/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteUsersRecipes(@PathVariable Long id) {
        boolean deleted = usersRecipesService.deleteUsersRecipes(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
