package com.hmaresc.TFG_Servidor.controller;

import com.hmaresc.TFG_Servidor.model.Recipe;
import com.hmaresc.TFG_Servidor.model.UserStats;
import com.hmaresc.TFG_Servidor.service.UserStatsService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/userstats")
public class UserStatsController {

    @Autowired
    private UserStatsService userStatsService;

    // .......................................................
    // .......................................................
    // .......................GET.............................
    // .......................................................
    // .......................................................
    // .......................................................
    // GET /userstats/
    // .......................................................
    @GetMapping
    public List<UserStats> getAllUserStats() {
        return userStatsService.getAllUserStats();
    }

    // .......................................................
    // GET /userstats/<id>
    // .......................................................
    @GetMapping("/{id}")
    public ResponseEntity<UserStats> getUserStatsById(@PathVariable Long id) {
        Optional<UserStats> recipe = userStatsService.getUserStatsById(id);

        if (recipe.isPresent()) {
            return ResponseEntity.ok(recipe.get());
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    // .......................................................
    // .......................................................
    // .......................POST............................
    // .......................................................
    // .......................................................
    // .......................................................
    // POST /userstats/
    // .......................................................
    @PostMapping
    public ResponseEntity<UserStats> createUserStats(@Valid @RequestBody UserStats userStats) {
        UserStats created = userStatsService.createUserStats(userStats);
        return ResponseEntity.ok(created);
    }

    // .......................................................
    // .......................................................
    // .....................UPDATE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // UPDATE /userstats/<id>
    // .......................................................
    @PutMapping("/{id}")
    public ResponseEntity<UserStats> updateUserStats(@PathVariable Long id, @Valid @RequestBody UserStats userStatsDetails) {
        Optional<UserStats> updatedUserStats = userStatsService.updateUserStats(id, userStatsDetails);
        return updatedUserStats.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    // .......................................................
    // .......................................................
    // .....................DELETE............................
    // .......................................................
    // .......................................................
    // .......................................................
    // DELETE /userstats/<id>
    // .......................................................
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteUserStats(@PathVariable Long id) {
        boolean deleted = userStatsService.deleteUserStats(id);
        if (deleted) {
            return ResponseEntity.noContent().build();
        }
        return ResponseEntity.notFound().build();
    }
}
