# ===============================
# SERVER CONFIG
# ===============================
spring.application.name=tfgservidor
server.port=8080

# ===============================
# DATABASE CONNET DATA
# ===============================
#spring.datasource.url=${POSTGRES_URL}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/nutricion_app
spring.datasource.username=rekken
spring.datasource.password=4848

# ===============================
# JPA/HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# LOCATION AND DATE FORMAT
# ===============================
spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=UTC

# ===============================
# LOGGING (DEBUG)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE